export const LANDING_2_SEQUENCE_IDS = {
  shell: "landing2Shell",
  stage: "stage",
  hero: "hero",
  lockInBtn: "l2-lock-in-btn",
  lockInBtnText: "l2-lock-in-btn-text",
  headline: "l2-headline",
  typed: "typed",
  banner: "l2-banner",
  wave: "l2-wave",
  statLine: "statLine",
  photo: "l2-photo",
  stageControls: "l2-stage-controls",
  pauseBtn: "l2-pause-btn",
  pauseIconPause: "l2-pause-icon-pause",
  pauseIconPlay: "l2-pause-icon-play",
  prevBtn: "l2-prev-btn",
  nextBtn: "l2-next-btn",
  influencerBadge: "l2-influencer-badge",
  achievement: (index: number) => `ach${index}`,
  achievementReaction: (index: number) => `achReaction${index}`,
} as const;
