export const QUERY_KEYS = {
  partners: "partners",
  schools: "schools",
  providers: "providers",
  lockins: "lockins",
  schoolsLockin: "schools-lockin",
  patientResults: "patientResults",
  patientResult: "patient-result",
  auth: "auth",
  user: "user",
  profile: "profile",
  specialties: "specialties",
  curator: "curator",
  curatorSummary: "curator-summary",
  curatorNotifications: "curator-notifications",
  providerSchoolsSummary: "provider-schools-summary",
  providerDashboard: "provider-dashboard",
  providerPatientDetails: "provider-patient-details",
  providerPatientActions: "provider-patient-actions",
  curatorProviderDetails: "curator-provider-details",
  curatorPatientModal: "curator-patient-modal",
  curatorPatientDetails: "curator-patient-details",
} as const;
