export const ROUTES = {
  public: {
    landing: "/",
    forProviders: "/for-providers",
    about: "/about",
    privacyPolicy: "/privacy-policy",
    termsAndConditions: "/terms-and-conditions",
    cookiePolicy: "/cookie-policy",
  },
  provider: {
    singIn: "/provider/auth?step=sign-in",
    signUp: "/provider/signup",
    checkEmail: "/provider/check-email",
    verifyEmail: "/provider/signup",
    verifyPasswordReset: "/provider/verify-password-reset",
    newPassword: "/provider/new-password",
    auth: "/provider/auth",
    profile: "/provider/profile",
    home: "/provider/home",
  },
  patient: {
    singIn: "/patient/signin",
    signUp: "/patient/signup",
    checkEmail: "/patient/check-email",
    verifyEmail: "/patient/signup",
    verifyPasswordReset: "/patient/verify-password-reset",
    newPassword: "/patient/new-password",
    lockIn: "/patient/lock-in",
    waitingRoom: "/patient/waiting-room",
  },
  curator: {
    dashboard: "/curator",
    schools: "/curator/schools",
    providers: "/curator/providers",
    partners: "/curator/partners",
    providerDetails: "/curator/provider",
  },
} as const;
