export { SchoolHeaderCard } from "./SchoolHeaderCard";
export { SchoolTabNavigation } from "./SchoolTabNavigation";
export type { SchoolTab } from "@/lib/types/components/curator/school-details";
export { PatientsTab } from "./PatientsTab";
export { IconsTab } from "./IconsTab";
export { default as UrgentPanel } from "@/components/shared/urgent-panel";
export { OverviewTab } from "./OverviewTab";
export { ProvidersTab } from "./ProvidersTab";
export { PartnersTab } from "./PartnersTab";
export { ReachTab } from "./ReachTab";
