import z from "zod/v4";

export const lockInSchema = z.object({
  campus: z.number(),
  reasonForLockin: z.string().min(1, "Reason is required"),
  timeToExam: z.string().min(1, "Time to exam is required"),
  fullName: z.string().min(1, "Full name is required"),
  age: z.number().min(1, "Age is required").max(150, "Invalid age"),
  sex: z.string().min(1, "Sex is required"),
  level: z.string().min(1, "Level is required"),
  feelingDepressed: z.string().min(1, "This field is required"),
  lossOfInterest: z.string().min(1, "This field is required"),
  feelingLonely: z.string().min(1, "This field is required"),
  suicidalThoughts: z.string().min(1, "This field is required"),
  suicidalPlans: z.string().min(1, "This field is required"),
  examWorrying: z.string().min(1, "This field is required"),
  sleepProblems: z.string().min(1, "This field is required"),
  fearOfFailure: z.string().min(1, "This field is required"),
  feelingNervous: z.string().min(1, "This field is required"),
  sweatingOrHeartRacing: z.string().min(1, "This field is required"),
  stomachUpset: z.string().min(1, "This field is required"),
  motivationToStudy: z.string().min(1, "This field is required"),
  focusWhileStudying: z.string().min(1, "This field is required"),
  activeStudying: z.string().min(1, "This field is required"),
  activeRecall: z.string().min(1, "This field is required"),
  lastMinuteStudying: z.string().min(1, "This field is required"),
});
